### ISSUE TITLE
pytorch_lora_weights.bin does not seem to be in the correct format expected by LoRA or Custom Diffusion training

### ISSUE THREAD

**Issue by wa-l-lll-l-ll** [Zeju1997/oft#21]
ValueError: log_oft/backpack-0/pytorch_lora_weights.bin does not seem to be in the correct format expected by LoRA or Custom Diffusion training.
[rank0]: Traceback (most recent call last):
[rank0]:   File "path_to_env/oft/oft-db/train_dreambooth_oft.py", line 1088, in <module>
[rank0]:     main(args)
[rank0]:   File "path_to_env/oft/oft-db/train_dreambooth_oft.py", line 1044, in main
[rank0]:     pipeline.unet.load_attn_procs(args.output_dir)
[rank0]:   File "path_to_env/lib/python3.9/site-packages/diffusers/loaders.py", line 332, in load_attn_procs
[rank0]:     raise ValueError(
[rank0]: ValueError: log_oft/backpack-0/pytorch_lora_weights.bin does not seem to be in the correct format expected by LoRA or Custom Diffusion training.

**Comment by rlgnswk** [comment]
Me Too

**Comment by Selena1105** [comment]
Have you resolved this problem?
